# Generated by Django 4.0.3 on 2022-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=10000)),
                ('author', models.CharField(max_length=150)),
                ('dateInit', models.DateTimeField(auto_now=True)),
                ('dateEnd', models.DateTimeField()),
            ],
        ),
    ]
